@extends('Shared::Layout.app')

@section('content')

{{--
|--------------------------------------------------------------------------
| MCF Authentication - Login
|--------------------------------------------------------------------------
|
| This is a starter authentication view generated by MCF.
|
| You may freely replace the entire UI with your own design.
|
| This view intentionally uses simple inline CSS and does not depend on
| any CSS framework.
|
| Expected Fields:
|
| - email
| - password
|
--}}

<style>
    .mcf-auth-card {
        width: 100%;
        max-width: 420px;
        margin: 60px auto;
        padding: 30px;
        border: 1px solid #ddd;
        border-radius: 10px;
    }

    .mcf-auth-title {
        text-align: center;
        margin-bottom: 25px;
    }

    .mcf-auth-field {
        margin-bottom: 18px;
    }

    .mcf-auth-field label {
        display: block;
        margin-bottom: 6px;
        font-weight: bold;
    }

    .mcf-auth-field input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 6px;
    }

    .mcf-auth-button {
        width: 100%;
        padding: 12px;
        cursor: pointer;
    }

    .mcf-auth-footer {
        margin-top: 20px;
        text-align: center;
    }

    .mcf-auth-footer div {
        margin-top: 10px;
    }

    .mcf-auth-checkbox {
        display: flex;
        align-items: center;
        gap: 8px;
        margin-bottom: 18px;
    }

    .mcf-auth-checkbox input[type="checkbox"] {
        width: auto;
        margin: 0;
        cursor: pointer;
    }

    .mcf-auth-checkbox label {
        margin: 0;
        cursor: pointer;
        font-weight: normal;
    }
</style>

<div class="mcf-auth-card">

    <h1 class="mcf-auth-title">

        {{ __('Login') }}

    </h1>


    <form method="POST" action="{{ route('user.auth.loginPost') }}">

        @csrf

        <div class="mcf-auth-field">

            <label for="email">
                {{ __('Email address') }}
            </label>

            <input id="email" type="email" name="email" value="{{ old('email') }}" autocomplete="email">

            @error('email')
            <div class="mcf-auth-error">
                {{ $message }}
            </div>
            @enderror

        </div>

        <div class="mcf-auth-field">

            <label for="password">
                {{ __('Password') }}
            </label>

            <input id="password" type="password" name="password" autocomplete="current-password">

            @error('password')
            <div class="mcf-auth-error">
                {{ $message }}
            </div>
            @enderror

        </div>

        <div class="mcf-auth-checkbox">

            <input id="remember" type="checkbox" name="remember" value="1" {{ old('remember') ? 'checked' : '' }}>

            <label for="remember">

                {{ __('Remember Me') }}

            </label>

        </div>

        <button type="submit" class="mcf-auth-button">

            {{ __('Login') }}

        </button>

    </form>

    <div class="mcf-auth-footer">

        <div>

            <a href="{{ route('user.auth.forgotPassword') }}">

                {{ __('Forgot Password?') }}

            </a>

        </div>

        <div>

            {{ __("Don't have an account?") }}

            <a href="{{ route('user.auth.register') }}">

                {{ __('Register') }}

            </a>

        </div>
        <br>   <br>
                <form method="POST" action="{{ route('shared.layout.switchLanguage') }}" class="mcf-profile-language">

            @csrf

            <select name="locale">

                <option value="en" {{ app()->getLocale() === 'en' ? 'selected' : '' }}
                    >
                    English
                </option>

                <option value="ar" {{ app()->getLocale() === 'ar' ? 'selected' : '' }}
                    >
                    العربية
                </option>

            </select>

            <button type="submit" class="mcf-profile-button">

                {{ __('Change Language') }}

            </button>

        </form>

    </div>

</div>

@endsection
