@extends('Shared::Layout.app')

@section('content')

{{--
|--------------------------------------------------------------------------
| MCF Authentication - Register
|--------------------------------------------------------------------------
|
| This is a starter authentication view generated by MCF.
|
| You may freely replace the entire UI with your own design.
|
| This view intentionally uses simple inline CSS and does not depend on
| any CSS framework.
|
| Expected Fields:
|
| - name
| - email
| - password
| - password_confirmation
|
--}}

<style>
    .mcf-auth-card {
        width: 100%;
        max-width: 420px;
        margin: 60px auto;
        padding: 30px;
        border: 1px solid #ddd;
        border-radius: 10px;
    }

    .mcf-auth-title {
        text-align: center;
        margin-bottom: 25px;
    }

    .mcf-auth-errors {
        margin-bottom: 20px;
        padding: 12px;
        border: 1px solid #f5c2c7;
        background: #f8d7da;
        color: #842029;
        border-radius: 6px;
    }

    .mcf-auth-field {
        margin-bottom: 18px;
    }

    .mcf-auth-field label {
        display: block;
        margin-bottom: 6px;
        font-weight: bold;
    }

    .mcf-auth-field input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 6px;
    }

    .mcf-auth-button {
        width: 100%;
        padding: 12px;
        cursor: pointer;
    }

    .mcf-auth-footer {
        margin-top: 20px;
        text-align: center;
    }
</style>

<div class="mcf-auth-card">

    <h1 class="mcf-auth-title">

        {{ __('Register') }}

    </h1>


    <form method="POST" action="{{ route('user.auth.registerPost') }}">

        @csrf

        <div class="mcf-auth-field">

            <label for="name">
                {{ __('Name') }}
            </label>

            <input id="name" type="text" name="name" value="{{ old('name') }}" autocomplete="name">

            @error('name')
            <div class="mcf-auth-error">
                {{ $message }}
            </div>
            @enderror

        </div>

        <div class="mcf-auth-field">

            <label for="email">
                {{ __('Email address') }}
            </label>

            <input id="email" type="email" name="email" value="{{ old('email') }}" autocomplete="email">

            @error('email')
            <div class="mcf-auth-error">
                {{ $message }}
            </div>
            @enderror

        </div>

        <div class="mcf-auth-field">

            <label for="phone">
                {{ __('Phone number') }}
            </label>

            <input id="phone" type="tel" name="phone" value="{{ old('phone') }}" maxlength="10" autocomplete="tel">

            @error('phone')
            <div class="mcf-auth-error">
                {{ $message }}
            </div>
            @enderror

        </div>

        <div class="mcf-auth-field">

            <label for="password">
                {{ __('Password') }}
            </label>

            <input id="password" type="password" name="password" autocomplete="new-password">

            @error('password')
            <div class="mcf-auth-error">
                {{ $message }}
            </div>
            @enderror

        </div>

        <div class="mcf-auth-field">

            <label for="password_confirmation">
                {{ __('Confirm password') }}
            </label>

            <input id="password_confirmation" type="password" name="password_confirmation" autocomplete="new-password">

            @error('password_confirmation')
            <div class="mcf-auth-error">
                {{ $message }}
            </div>
            @enderror

        </div>

        <button type="submit">
            {{ __('Create account') }}
        </button>

    </form>

    <div class="mcf-auth-footer">

        {{ __('Already have an account?') }}

        <a href="{{ route('user.auth.login') }}">

            {{ __('Login') }}

        </a>

    </div>

</div>

@endsection
